<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
class DegreeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $degrees = [
            [
                'education_level_id'=>'1',
                'name' => 'PSC',
                'short_name' => 'psc',
                'description' => '',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'1',
                'name' => 'Ebtedayee (Madrasah)',
                'short_name' => 'ebtedayee-madrasah',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'1',
                'name' => '5 Pass',
                'short_name' => '5-pass',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'2',
                'name' => 'JSC',
                'short_name' => 'jsc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'2',
                'name' => 'JDC (Madrasah)',
                'short_name' => 'jdc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'2',
                'name' => '8 Pass',
                'short_name' => '8-pass',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'3',
                'name' => 'SSC',
                'short_name' => 'ssc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'3',
                'name' => 'O Level',
                'short_name' => 'o-level',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'3',
                'name' => 'Dakhil (Madrasah)',
                'short_name' => 'dakhil',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'3',
                'name' => 'SSC (Vocational)',
                'short_name' => 'ssc-vocational)',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'4',
                'name' => 'HSC',
                'short_name' => 'hsc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'4',
                'name' => 'A Level',
                'short_name' => 'a-level',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'4',
                'name' => 'Alim (Madrasah)',
                'short_name' => 'alim-madrasah',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'4',
                'name' => 'HSC (Vocational)',
                'short_name' => 'hsc-vocational',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Engineering',
                'short_name' => 'Diploma-in-Engineering',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Medical Technology',
                'short_name' => 'Diploma-in-Medical-Technology',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Nursing',
                'short_name' => 'Diploma-in-Nursing',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Commerce',
                'short_name' => 'Diploma-in-Commerce',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],[
                'education_level_id'=>'5',
                'name' => 'Diploma in Business Studies',
                'short_name' => 'Diploma-in-Business-Studies',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Post Graduate Diploma (PGD)',
                'short_name' => 'PGD',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Pathology',
                'short_name' => 'Diploma-in-Pathology',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma(Vocational)',
                'short_name' => 'Diploma(Vocational)',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'5',
                'name' => 'Diploma in Hotel Management',
                'short_name' => 'DHM',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Science (BSc)',
                'short_name' => 'BSc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Arts (BA)',
                'short_name' => 'BA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Commerce (BCom)',
                'short_name' => 'BCom',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Commerce (Pass)',
                'short_name' => 'BC-Pass',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Business Administration (BBA)',
                'short_name' => 'BBA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Medicine and Bachelor of Surgery(MBBS)',
                'short_name' => 'MBBS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Dental Surgery (BDS)',
                'short_name' => 'BDS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Architecture (B.Arch)',
                'short_name' => 'B.Arch',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Pharmacy (B.Pharm)',
                'short_name' => 'B.Pharm',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Education (B.Ed)',
                'short_name' => 'B.Ed',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Physical Education (BPEd)',
                'short_name' => 'BPEd',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Law (LLB)',
                'short_name' => 'LLB',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Doctor of Veterinary Medicine (DVM)',
                'short_name' => 'DVM',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Social Science (BSS)',
                'short_name' => 'BSS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Fine Arts (B.F.A)',
                'short_name' => 'B.F.A',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Business Studies (BBS)',
                'short_name' => 'BBS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor of Computer Application (BCA)',
                'short_name' => 'BCA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Fazil (Madrasah)',
                'short_name' => 'Fazil',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'6',
                'name' => 'Bachelor in Engineering (BEngg)',
                'short_name' => 'BEngg',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Science (MSc)',
                'short_name' => 'MSc',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Arts (MA)',
                'short_name' => 'MA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Commerce (MCom)',
                'short_name' => 'MCom',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Business Administration (MBA)',
                'short_name' => 'MBA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Architecture (M.Arch)',
                'short_name' => 'M.Arch',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Pharmacy (M.Pharm)',
                'short_name' => 'M.Pharm',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],[
                'education_level_id'=>'7',
                'name' => 'Master of Education (M.Ed)',
                'short_name' => 'M.Ed',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Law (LLM)',
                'short_name' => 'LLM',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Social Science (MSS)',
                'short_name' => 'MSS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
              [
                'education_level_id'=>'7',
                'name' => 'Master of Fine Arts (M.F.A)',
                'short_name' => 'M.F.A',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Philosophy (M.Phil)',
                'short_name' => 'M.Phil',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
              [
                'education_level_id'=>'7',
                'name' => 'Master of Business Management (MBM)',
                'short_name' => 'MBM',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Development Studies (MDS)',
                'short_name' => 'MDS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Master of Business Studies (MBS)',
                'short_name' => 'MBS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Masters in Computer Application (MCA)',
                'short_name' => 'MCA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Executive Master of Business Administration (EMBA)',
                'short_name' => 'EMBA',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Fellowship of the College of Physicians and Surgeons (FCPS)',
                'short_name' => 'FCPS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Kamil (Madrasah)',
                'short_name' => 'Kamil',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Masters in Engineering (MEngg)',
                'short_name' => 'MEngg',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

 [
                'education_level_id'=>'7',
                'name' => 'Masters in Bank Management (MBM)',
                'short_name' => 'MBM',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'education_level_id'=>'7',
                'name' => 'Masters in Information Systems Security (MISS)',
                'short_name' => 'MISS',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

 [
                'education_level_id'=>'7',
                'name' => 'Master of Information & Communication Technology (MICT)',
                'short_name' => 'MICT',
                'description' => ' ',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ]
        ];
        DB::table('degrees')->insert($degrees);

    }
}
