<?php

use Illuminate\Database\Seeder;
use Faker\Factory;
use Carbon\Carbon;
class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            //Permission Category
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Permission Category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new permission category form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Permission Category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit permission category form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
//Permission
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new permission form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit permission form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Roles Service
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'index',
                  'allowed' => '1',
                  'display' => 'Show all Roles',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'create',
                  'allowed' => '1',
                  'display' => 'Open new role form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'show',
                  'allowed' => '1',
                  'display' => 'Show the single Role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'allowed' => '1',
                  'display' => 'Open edit role form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'POST',
                  'action' => 'store',
                  'allowed' => '1',
                  'display' => 'Create a new role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'allowed' => '1',
                  'display' => 'Update role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'allowed' => '1',
                  'display' => 'Delete a role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ]
        ];
        DB::table('permissions')->insert($permissions);
    }
}
